migrate to Vonage namespace
Vonage/vonage-ruby-code-snippets pull request #76
Opened 2020-09-01 07:21 UTC by bencgreenberg

This PR is dependent on the migration first of the Ruby SDK to the Vonage namespace and its publication to Rubygems.

2020-09-09 14:16 UTC, kellyjandrews requested changes
Just a couple of things to look at and address. Otherwise looks ok from my side.

2020-09-09 14:16 UTC, kellyjandrews commented on LICENSE.md
> +Copyright (c) 2020 Vonage Community
Also remove the (c)

2020-09-09 14:16 UTC, kellyjandrews commented on README.md
> +Please [raise an issue](https://github.com/Nexmo/nexmo-ruby-code-snippets/issues) to request an example that isn't present within
I think this moved to Vonage, correct?

2020-09-09 17:59 UTC, kellyjandrews requested changes
Update the image, and I think it's ready to go.

2020-09-09 17:59 UTC, kellyjandrews commented on README.md
>  <img src="https://developer.nexmo.com/assets/images/Vonage_Nexmo.svg" height="48px" alt="Nexmo is now known as Vonage" />
I'd say swap it with this one - https://developer.nexmo.com/images/logos/vbc-logo.svg

2020-09-10 12:30 UTC, bencgreenberg commented on README.md
>  <img src="https://developer.nexmo.com/assets/images/Vonage_Nexmo.svg" height="48px" alt="Nexmo is now known as Vonage" />
```suggestion
<img src=" https://developer.nexmo.com/images/logos/vbc-logo.svg" height="48px" alt="Vonage APIs" />
```

2020-09-10 13:26 UTC, kellyjandrews approved these changes
lgtm

2020-09-10 13:29 UTC, merged